Navbar
Manuel-Antunes/taverna-de-mordor-adonis pull request #74
Opened 2022-01-25 04:56 UTC by guilherme-gjv

# Related Issue
- #73 

# Proposed Changes
- New font families implemented;
- Darker navbar;
- Hexagon icon design implemented;

# Additional Info
- any additional information or context

# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentation

# Screenshots
>## PC
> ![navbar](https://user-images.githubusercontent.com/83377948/150912961-06035018-fe01-4abd-9e85-d12dee188d60.PNG)

>## Mobile
> ![navbarm](https://user-images.githubusercontent.com/83377948/150912959-edd42d10-ff50-4278-8fd7-10bb55ffb542.PNG)
>
> ![navbarmo](https://user-images.githubusercontent.com/83377948/150912957-7f2bdf4c-a4e0-4714-bfcb-a5fba2c8af34.PNG)

2022-01-26 03:13 UTC, Manuel-Antunes requested changes
there's a reference of `Cinzel` in fonts, but, it isn't imported in anywhere and the hexagon isn't good

2022-01-26 03:23 UTC, leticiabsduarte requested changes
The font needs to be imported, please correct it.
Improve the hexagon icon, try to make it more like the original ideia

2022-01-26 04:14 UTC, guilherme-gjv commented
![tempsnip](https://user-images.githubusercontent.com/83377948/151102922-533821eb-93f1-4ced-8d59-63a90a5d25c1.png)

2022-01-26 04:47 UTC, guilherme-gjv commented
# 👌 

![sim](https://user-images.githubusercontent.com/83377948/151105454-8d4d1845-e2c3-434b-ad69-0a863ab4e17d.PNG)

2022-01-27 01:21 UTC, Manuel-Antunes approved these changes
Please, import fonts in css instead of html

2022-01-27 01:21 UTC, Manuel-Antunes commented on resources/views/layouts/main.edge
> +  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
```suggestion
  <link href="https://fonts.googleapis.com/css?family=Cinzel:400" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
```

please, import font in app.css

2022-01-27 01:37 UTC, leticiabsduarte approved these changes
The user icon is perfect, but now put the notification dot, it's important. Good job =)

2022-01-28 02:07 UTC, merged