Board review
Manuel-Antunes/taverna-de-mordor-adonis pull request #78
Opened 2022-01-30 15:36 UTC by duardoqueiroz

# Proposed Changes
- implement board review system

# Aditional info 
- need to configure editing review

# Screenshots
> # Updated
![image](https://user-images.githubusercontent.com/83377894/151706270-39c78301-c72e-4f4f-9be9-da05beeae9e8.png)
![image](https://user-images.githubusercontent.com/83377894/151706287-ee42d910-0265-47ab-b79d-454a8f315b13.png)

2022-01-31 18:48 UTC, leticiabsduarte requested changes
- Let only one number after dot, and change it to a comma
![estrelinhas](https://user-images.githubusercontent.com/84350666/151853125-20e50d8b-a646-4eb7-ae97-0076ac3a2244.PNG)

- Each commentary has your account with your different icon. Fix this error with the icons profile
![resenharesenha](https://user-images.githubusercontent.com/84350666/151853208-51a082cd-7745-4582-acd2-835d0d407aa9.PNG)

- I believe you have access to the Figma of this site, always make it exactly what Stanislav did
![original russo](https://user-images.githubusercontent.com/84350666/151859866-df2871a4-e7ea-48e8-9977-151dc30beb46.PNG)
![original russo 2](https://user-images.githubusercontent.com/84350666/151859890-5c9b53ab-ea33-45eb-95d1-09f7c2c06f9c.PNG)

2022-02-03 01:53 UTC, Manuel-Antunes requested changes
Check my issues

2022-02-03 01:53 UTC, Manuel-Antunes commented on app/Models/Board.ts
> +            return parseFloat(count.toString()) + parseFloat(el.toString())
If you wan't to use this field, remove unused computed `reviewNumber`

2022-02-03 01:53 UTC, Manuel-Antunes commented on app/Models/Event.ts
> +            return parseInt(count.toString()) + parseInt(el.toString())
```suggestion
            return parseInt(count.toString(), 10) + parseInt(el.toString(), 10)
```
add radix to parseInt function

2022-02-03 01:53 UTC, Manuel-Antunes commented on app/Models/User.ts
> +            return parseInt(count.toString()) + parseInt(el.toString())
```suggestion
            return parseInt(count.toString(), 10) + parseInt(el.toString(), 10)
```
add radix

2022-02-03 01:53 UTC, Manuel-Antunes commented on resources/views/components/hexagonal-photo.edge
> +<div class="hex flex relative" style="-webkit-clip-path: polygon(50% 1%, 95% 25%, 95% 75% ,50% 99%, 5% 75%, 5% 25%);
Turn this style tag into a custom class in tailwind called `hexagon`

2022-02-03 12:03 UTC, leticiabsduarte requested changes
- This is what happens when there are a big commentary and more than two reviews, fix it.

![avaliação erro](https://user-images.githubusercontent.com/84350666/152338517-41f73782-c8de-42e1-aa19-ed1485b46359.PNG)

![avaliação erro 2](https://user-images.githubusercontent.com/84350666/152338533-2042ec4e-6547-45dd-9ec9-6be23c632227.PNG)
- The icons profile keeps on bug

- Add the half star in ratings, as figma

![original russo 2](https://user-images.githubusercontent.com/84350666/152339556-ddfdac99-d46a-4af0-8085-344eb4093448.PNG)

2022-02-03 12:30 UTC, duardoqueiroz commented
> the bugs are already fixed. Please try to git pull the modifications.
![image](https://user-images.githubusercontent.com/83377894/152342963-0549699a-fd7f-42d5-911f-6aad12ccc3d8.png)
#
![image](https://user-images.githubusercontent.com/83377894/152342912-3de9febb-c37c-47b6-9ecb-4aa96e0d99b5.png)

2022-02-03 13:00 UTC, leticiabsduarte commented
> > the bugs are already fixed. Please try to git pull the modifications. @leticiabsduarte
> > [#78 (review)](https://github.com/Manuel-Antunes/taverna-de-mordor-adonis/pull/78#pullrequestreview-871744983)
> > ![image](https://user-images.githubusercontent.com/83377894/152342963-0549699a-fd7f-42d5-911f-6aad12ccc3d8.png)
> 
> ![image](https://user-images.githubusercontent.com/83377894/152342912-3de9febb-c37c-47b6-9ecb-4aa96e0d99b5.png)

my bad, it's all perfect now =)

2022-02-03 13:00 UTC, leticiabsduarte approved these changes
good work!

2022-02-03 14:22 UTC, Manuel-Antunes approved these changes
Please, move hexagon class to tailwind config

2022-02-05 02:06 UTC, merged

2022-02-05 02:06 UTC, guilherme-gjv commented
## Dudu asked me to merge it...