Master review
Manuel-Antunes/taverna-de-mordor-adonis pull request #81
Opened 2022-02-04 03:58 UTC by duardoqueiroz

# Proposed Changes
- User profile card
- Master review system

# Screenshots

> ## Update
![image](https://user-images.githubusercontent.com/83377894/152468823-697dc074-a037-4c70-9540-0499f10ff3f0.png)
> #
![image](https://user-images.githubusercontent.com/83377894/152468858-3b1dc73b-7a42-4364-add4-cbfa8db79f0e.png)
> #
![image](https://user-images.githubusercontent.com/83377894/152469480-bfc6dba0-3305-47e9-9fed-1a1207a291de.png)

2022-02-05 02:17 UTC, leticiabsduarte approved these changes
It looks perfect, good work =)

2022-02-09 12:40 UTC, Manuel-Antunes requested changes
Check my comments, solve, and request my review again

2022-02-09 12:40 UTC, Manuel-Antunes commented on resources/views/components/review-edit.edge
> +    } }" data-limit="300" ,
Please, move this state to app.js

2022-02-09 12:40 UTC, Manuel-Antunes commented on resources/views/components/review-form.edge
> +</style>
Try to config this styles in head

2022-02-09 12:40 UTC, Manuel-Antunes commented on resources/views/components/star-rating.edge
> +<div x-data="{ temp: 0, orig: 0 }" class="flex cursor-pointer" @click="orig = temp">
Call this state from app.js

2022-02-09 12:40 UTC, Manuel-Antunes commented on resources/views/components/star-value.edge
> +}" class="flex flex-row">
Call this state from app.js

2022-02-09 12:40 UTC, Manuel-Antunes commented on resources/views/users/index.edge
> +<section class="bg-gray-900 h-full" x-data="{contentId:1}">
call this state from app.js

2022-02-19 17:10 UTC, leticiabsduarte approved these changes
I got lost looking for where to review the master, but it keeps perfect to me. Good work!

2023-01-03 00:10 UTC, closed without merging