Make it api only
Manuel-Antunes/taverna-de-mordor-adonis pull request #91
Opened 2022-07-18 16:42 UTC by Lucas-Marques-Leao

# Related Issue
- #90 

# Proposed Changes
- every frontend resource was deleted except for adonis session and its configuration
- auth contract converted to "api" contract

# Additional Info
- This branch never pushes its info to the project's main branch, Dudu, don't kill me

2022-07-19 00:26 UTC, Manuel-Antunes requested changes
90 files ????? no i'll not review this

2022-07-19 12:29 UTC, duardoqueiroz reviewed
Ok! Repproved :)

2022-07-19 12:29 UTC, duardoqueiroz commented on config/ally.ts
> +    callbackUrl: 'http://localhost:3000/auth/google',
change to environment

2022-12-16 00:37 UTC, duardoqueiroz requested changes
Please, solve my suggestions.

- Remove 'create' and 'edit' methods in crontrollers.

2022-12-16 00:37 UTC, duardoqueiroz commented on app/Controllers/Http/EventsController.ts
>    }
Remove this method

2022-12-16 00:37 UTC, duardoqueiroz commented on app/Controllers/Http/EventsController.ts
> +    return event
remove this method

2022-12-16 00:37 UTC, duardoqueiroz commented on docker-compose.yml
> +      - '27017:27017'
please, create environment to mongodb port

2022-12-24 01:20 UTC, closed without merging